version: '3.3'

services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception

  nginx:
    image: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception

volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cmarien/data/wp'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cmarien/data/db'

networks:
    inception:
